name: names_generator
description: Docker's namesgenerator in Dart
version: 0.1.0
author: Kwang Yul Seo <email@example.com>
homepage: https://github.com/kseo/names_generator

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
